version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    cmds:
      - pnpm install
      - pnpm prune
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm build
    sources:
      - .eslintrc.cjs
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - vite.config.ts
      - src/*
    generates:
      - dist/*

  story-dev:
    desc: Story - Dev
    deps: [ install ]
    cmds:
      - pnpm run story:dev

  story-build:
    desc: Story - Build
    deps: [ install ]
    cmds:
      - rm -rf build/histoire
      - pnpm run story:build
    sources:
      - .eslintrc.cjs
      - histoire.config.ts
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - vite.config.ts
      - src/*
      - src/stories/*
    generates:
      - build/histoire/*

  site-build:
    desc: Site - Build
    deps: [ story-build ]
    cmds:
      - rm -rf build/site
      - mkdir -p build/site/svelte-timetable
      - cp -r build/histoire/* build/site/svelte-timetable/
      - touch build/site/svelte-timetable/.nojekyll
    generates:
      - build/site/*

  site-serve:
    desc: Site - Serve
    deps: [ site-build ]
    cmds:
      - pnpm dlx sirv-cli@0.4.6 --cors --port 8080 build/site

  site-publish:
    desc: Site - Publish
    deps: [ site-build ]
    cmds:
      - gh-pages --dotfiles --dist build/site/svelte-timetable

  npm-publish:
    desc: NPM - Publish
    deps: [ build ]
    cmds:
      - pnpm publish --access public
